# Generated by Django 2.0.7 on 2018-07-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cover_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cover_img_item', to='main.Image'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Image'),
        ),
    ]
