# Generated by Django 2.0.7 on 2018-07-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180722_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.Category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
